server:
  port: 8080


#spring:
#
#  application:
#    name: "testserver"
#  profiles:
#    active: "prod"
#  config:
#    import: "configserver:http://localhost:8090/"
#  data:
#    redis:
#      host: localhost
#      port: 6379

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest




spring:
  application:
    name: "testserver"
  data:
    redis:
      host: localhost
      port: 6379

ratelimiter:
  global:
    limit: 200
    duration: 1m
    keyType: USER

  apis:
    test-api:
      keyType: USER
      limit: 0
      duration: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    prometheus:
      enabled: true