ratelimiter:
  global:
    limit: 200
    duration: 1
    keyType: USER

  apis:
    global-api:
      keyType: USER
      limit: 1
      duration: 10
    test-api:
      keyType: USER
      limit: 1
      duration: 10